/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
fun rectangulo() {
    val base: Double = 20.5
    val altura: Double = 14.5
    val area: Double = base*altura
    println("$area")
}
fun nombre(){
    val nombre: String = "mateo"
    val fecha: Double = 22.04
    val años: Int = 16
    val esEstudiante: Boolean = true
    println("$nombre, $fecha, $años, $esEstudiante")
}
fun main() {
    nombre()
    rectangulo()
}
