/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun esParOImpar(numero: Int): String {
    return when {
        numero % 2 == 0 -> "Par"
        else -> "Impar"
    }
}
fun positivonegativocero(numero: Int) {
    if (numero > 0) {
        println("positivo")
    } else {
        if (numero < 0) {
            println("negativo")
        } else {
            println(0)
        }
    }
}

fun rectangulo() {
    val base: Double = 20.5
    val altura: Double = 14.5
    val area: Double = base*altura
    println("$area")
}
fun nombre(){
    val nombre: String = "mateo"
    val fecha: Double = 22.04
    val años: Int = 16
    val esEstudiante: Boolean = true
    println("$nombre, $fecha, $años, $esEstudiante")
}
fun main() {
    nombre()
    rectangulo()
    val numero = 10
    println(esParOImpar(numero))
    positivonegativocero(numero)
}
